text2workspace.py Datacard.txt -m 125.0  -P HiggsAnalysis.CombinedLimit.FA3_Interference_JHU_ggHSyst_rw_MengsMuV_HeshyXsec_ggHInt_ggHphase:FA3_Interference_JHU_ggHSyst_rw_MengsMuV_HeshyXsec_ggHInt_ggHphase  -o Datacard.root

python combineTool.py -M MultiDimFit Datacard.root -n _scan_exp_fa3_ggH_from_AC_HGG_HPlus2Jets -m 125 --freezeParameters MH --algo=grid --alignEdges 1 --points=160  -P fa3_ggH --floatOtherPOIs=1 --setParameterRanges muV=0,5:mu_ggH=0,5:fa3_ggH=-1,1:fa3=-1,1 --setParameters muV=1,mu_ggH=1,fa3_ggH=0,fa3=0 --X-rtd MINIMIZER_analytic --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 1 -t -1 -v 2 --job-mode condor --split-points 10 --robustFit=1 --sub-opts='+JobFlavour="workday"' --task-name mytask 

python combineTool.py --floatOtherPOIs 1 -P fa3_ggH --algo grid --alignEdges 1 --redefineSignalPOIs fa3_ggH,fa3,mu_ggH,muV --saveSpecifiedNuis all --saveInactivePOI 1 --setParameters muV=1.0,fa3_ggH=0.0,mu_ggH=1.0,fa3=0.0 --setParameterRanges muV=0.0,4.0:mu_ggH=0.0,10.0:fa3_ggH=-1.0,1.0:fa3=0.0,0.001 --robustFit=1 --setRobustFitAlgo=Minuit2,Migrad --X-rtd FITTER_NEW_CROSSING_ALGO --setRobustFitTolerance=0.2 --X-rtd FITTER_NEVER_GIVE_UP --X-rtd FITTER_BOUND --cminFallbackAlgo Minuit2,0:1. --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d Datacard_RunII.root --points 40 -n _scan1D_syst_only_fa3_ggH.RunII --setCrossingTolerance 0.000001 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 -v 1 --job-mode condor --split-points 10 --robustFit=1 --sub-opts='+JobFlavour="workday"' --task-name  mytask

python combineTool.py -M MultiDimFit Datacard_RunII.root -n .observed_scan.with_syst -m 125.38 --floatOtherPOIs 1 -P fa3_ggH --algo grid --alignEdges 1 --redefineSignalPOIs fa3_ggH,fa3,mu_ggH,muV --saveSpecifiedNuis all --saveInactivePOI 1 --setParameters muV=1.0,fa3_ggH=0.0,mu_ggH=1.0,fa3=0.0 --setParameterRanges muV=0.0,4.0:mu_ggH=0.0,10.0:fa3_ggH=-1.0,1.0:fa3=0.0,0.001 

python combineTool.py --floatOtherPOIs 1 -P muV --algo grid --alignEdges 1 --redefineSignalPOIs fa3_ggH,fa3,mu_ggH,muV --saveSpecifiedNuis all --saveInactivePOI 1 --setParameters muV=1.0,fa3_ggH=0.0,mu_ggH=1.0,fa3=0.0 --setParameterRanges muV=0.0,5.0:mu_ggH=0.0,10.0:fa3_ggH=-1.0,1.0:fa3=0.0,0.001 --robustFit=1 --setRobustFitAlgo=Minuit2,Migrad --X-rtd FITTER_NEW_CROSSING_ALGO --setRobustFitTolerance=0.2 --X-rtd FITTER_NEVER_GIVE_UP --X-rtd FITTER_BOUND --cminFallbackAlgo Minuit2,0:1. --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2 -M MultiDimFit -m 125.38 -d Datacard_RunII.root --points 80 -n _scan1D_syst_new_exp_muV.RunII --setCrossingTolerance 0.000001 --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 -t -1 -v 1 --job-mode condor --split-points 10 --sub-opts='+JobFlavour="workday"' --task-name  mytask
